### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by JackMwangi** [gangachris/angular2-validators#3]
Tests are missing

**Comment by abiodun0** [comment]
If there are no takers.. Am willing to work on this... ¯\_(ツ)_/¯

**Comment by gangachris** [comment]
Sure @abiodun0

**Comment by gangachris** [comment]
Current state and thinking. [Validators](https://github.com/chriso/validator.js), is already well tested. Wondering whether the approach should be to test the demo app instead.

**Comment by abiodun0** [comment]
@gangachris .. been thinking about the same thing. but we might have to test all the utility functions that we create. at least to make sure they return the instance of the validator function we are testing :)
